"""init with char, relics & light cones.

Revision ID: 405808fdbf19
Revises:
Create Date: 2026-04-14 19:39:33.452963

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "405808fdbf19"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
